import json
import re
from pathlib import Path

INPUT_FILE = Path("dictionary/cedict_ts.u8")
OUTPUT_FILE = Path("dictionary.js")

TONE_MARKS = {
    "a": ["ā", "á", "ǎ", "à"],
    "e": ["ē", "é", "ě", "è"],
    "i": ["ī", "í", "ǐ", "ì"],
    "o": ["ō", "ó", "ǒ", "ò"],
    "u": ["ū", "ú", "ǔ", "ù"],
    "v": ["ǖ", "ǘ", "ǚ", "ǜ"],
}


def numbered_to_tone(syllable):
    match = re.match(r"^([a-züv]+)([0-5])$", syllable.lower())

    if not match:
        return syllable

    letters = match.group(1)
    tone = int(match.group(2))

    if tone == 5:
        return letters

    vowel_index = None

    # a or e gets the tone
    for vowel in ["a", "e"]:
        if vowel in letters:
            vowel_index = letters.index(vowel)
            break

    # "ou" puts the tone on o
    if vowel_index is None and "ou" in letters:
        vowel_index = letters.index("o")

    # Otherwise put it on the last vowel
    if vowel_index is None:
        for i in range(len(letters) - 1, -1, -1):
            if letters[i] in "aeiouvü":
                vowel_index = i
                break

    if vowel_index is None:
        return syllable

    vowel = letters[vowel_index]

    if vowel in ["ü", "v"]:
        vowel_key = "v"
    else:
        vowel_key = vowel

    marked_vowel = TONE_MARKS[vowel_key][tone - 1]

    return (
        letters[:vowel_index]
        + marked_vowel
        + letters[vowel_index + 1:]
    )


def convert_pinyin(pinyin):
    return " ".join(
        numbered_to_tone(syllable)
        for syllable in pinyin.split()
    )


dictionary = {}

with INPUT_FILE.open("r", encoding="utf-8") as file:

    for line in file:

        line = line.strip()

        if not line or line.startswith("#"):
            continue

        match = re.match(
            r"^(\S+)\s+(\S+)\s+\[([^\]]+)\]",
            line
        )

        if not match:
            continue

        traditional = match.group(1)
        simplified = match.group(2)
        pinyin = match.group(3)

        pinyin = convert_pinyin(pinyin)

        def add_entry(word, pinyin):
            if word not in dictionary:
                dictionary[word] = []

            if pinyin not in dictionary[word]:
                dictionary[word].append(pinyin)


        add_entry(simplified, pinyin)
        add_entry(traditional, pinyin)




print(f"Loaded {len(dictionary):,} dictionary entries.")

with OUTPUT_FILE.open("w", encoding="utf-8") as file:

    file.write("// Generated from CC-CEDICT\n")
    file.write("// CC BY-SA 4.0\n")
    file.write("// Do not edit this file manually.\n\n")

    file.write("const PINYIN_DICTIONARY = ")

    json.dump(
        dictionary,
        file,
        ensure_ascii=False,
        separators=(",", ":")
    )

    file.write(";\n")

print(f"Created {OUTPUT_FILE}")
